"""
SoccerNet-GSR Canonical Tracking Adapter.

Provides validation and loading functions for canonical tracking data
generated by the SoccerNet-GSR perception pipeline.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional, Union

import numpy as np
import pandas as pd


CANONICAL_COLUMNS = [
    "match_id",
    "frame",
    "timestamp",
    "player_id",
    "team",
    "x",
    "y",
    "confidence",
    "visible",
]


def validate_gsr_canonical_tracking(df: pd.DataFrame) -> None:
    """
    Strict validation of GSR tracking DataFrame against Canonical Tracking Schema v0.2.0.

    Raises:
        ValueError: If any canonical rule is violated.
    """
    missing_cols = set(CANONICAL_COLUMNS) - set(df.columns)
    if missing_cols:
        raise ValueError(f"GSR tracking data missing canonical columns: {missing_cols}")

    if df["match_id"].isna().any() or (df["match_id"] == "").any():
        raise ValueError("match_id must be populated and non-empty for all rows.")

    if not pd.api.types.is_integer_dtype(df["frame"]):
        raise ValueError("frame column must be of integer data type.")

    if not pd.api.types.is_numeric_dtype(df["timestamp"]):
        raise ValueError("timestamp column must be numeric.")

    if not pd.api.types.is_bool_dtype(df["visible"]):
        raise ValueError("visible column must be boolean.")

    if not pd.api.types.is_numeric_dtype(df["confidence"]):
        raise ValueError("confidence column must be numeric.")

    if (df["confidence"] < 0.0).any() or (df["confidence"] > 1.0).any():
        raise ValueError("confidence values must be bounded within [0.0, 1.0].")

    valid_teams = {"home", "away", "referee"}
    invalid_teams = set(df["team"].unique()) - valid_teams
    if invalid_teams:
        raise ValueError(f"Invalid team values found in GSR tracking: {invalid_teams}")

    dups = df.duplicated(subset=["match_id", "frame", "team", "player_id"])
    if dups.any():
        raise ValueError(f"Found {dups.sum()} duplicate player entries per frame in GSR tracking.")


def load_canonical_gsr_tracking(
    csv_path: Union[str, Path],
    expected_match_id: Optional[str] = None,
) -> pd.DataFrame:
    """
    Loads and validates a canonical GSR tracking CSV.

    Args:
        csv_path: Path to the canonical GSR tracking CSV.
        expected_match_id: Optional match ID to verify against.

    Returns:
        Validated pandas DataFrame in canonical schema.
    """
    path = Path(csv_path)
    if not path.exists():
        raise FileNotFoundError(f"GSR tracking file not found at: {path}")

    df = pd.read_csv(path)
    
    # Cast dtypes
    df["match_id"] = df["match_id"].astype(str)
    df["frame"] = df["frame"].astype(int)
    df["timestamp"] = df["timestamp"].astype(float)
    df["player_id"] = df["player_id"].astype(str)
    df["team"] = df["team"].astype(str)
    df["x"] = df["x"].astype(float)
    df["y"] = df["y"].astype(float)
    df["confidence"] = df["confidence"].astype(float)
    df["visible"] = df["visible"].astype(bool)

    if expected_match_id and not (df["match_id"] == expected_match_id).all():
        raise ValueError(f"match_id mismatch: expected '{expected_match_id}', found {df['match_id'].unique()}")

    validate_gsr_canonical_tracking(df)
    return df[CANONICAL_COLUMNS]
